name = "filament-manager"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "FILAMENT_DB"
database_name = "filament-db"
database_id = "774825ed-a28a-4a80-b1b3-d6a47ca0414a"
