name = "filament-manager"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "FILAMENT_DB"
database_name = "filament-db"
database_id = "bd3a2e07-84e2-419b-bed7-4d80b0a7714b"
